package com.novaemu.protocol.composers;

import java.lang.reflect.Field;

public class Incoming
{
	public static int InitCryptoMessageEvent = 206;
	public static int GenerateSecretKeyMessageEvent = 2002;
	public static int VersionCheckMessageEvent = 1170;
	public static int UniqueIDMessageEvent = 813;
	public static int GetSessionParametersMessageEvent = 1817;
	public static int SSOTicketMessageEvent = 415;
	public static int TryLoginMessageEvent = 756;
	public static int PongMessageEvent = 196;
	public static int InfoRetrieveMessageEvent = 7;
	public static int DisconnectMessageEvent = 512;
	public static int MessengerInitMessageEvent = 12;
	public static int FriendListUpdateMessageEvent = 15;
	public static int SendMsgMessageEvent = 33;
	public static int AcceptBuddyMessageEvent = 37;
	public static int DeclineBuddyMessageEvent = 38;
	public static int RequestBuddyMessageEvent = 39;
	public static int RemoveBuddyMessageEvent = 40;
	public static int HabboSearchMessageEvent = 41;
	public static int GetBuddyRequestsMessageEvent = 233;
	public static int FollowFriendMessageEvent = 262;
	public static int SendRoomInviteMessageEvent = 34;
	public static int FindNewFriendsMessageEvent = 490;
	public static int GetEventStreamEvent = 500;
	public static int SetEventStreamingAllowedEvent = 501;
	public static int GetCreditsInfoEvent = 8;
	public static int RequestFurniInventoryEvent = 404;
	public static int AvatarEffectSelectedEvent = 372;
	public static int AvatarEffectActivatedEvent = 373;
	public static int GetBadgesEvent = 157;
	public static int SetActivatedBadgesEvent = 158;
	public static int GetBadgePointLimitsEvent = 3032;
	public static int GetAchievementsEvent = 370;
	public static int UnacceptTradingEvent = 68;
	public static int AcceptTradingEvent = 69;
	public static int CloseTradingEvent = 70;
	public static int OpenTradingEvent = 71;
	public static int AddItemToTradeEvent = 72;
	public static int ConfirmAcceptTradingEvent = 402;
	public static int ConfirmDeclineTradingEvent = 403;
	public static int RemoveItemFromTradeEvent = 405;
	public static int GetPetInventoryEvent = 3000;
	public static int MakeOfferMessageEvent = 3010;
	public static int GetMarketplaceConfigurationMessageEvent = 3011;
	public static int GetMarketplaceCanMakeOfferEvent = 3012;
	public static int BuyMarketplaceTokensMessageEvent = 3013;
	public static int BuyOfferMessageEvent = 3014;
	public static int CancelOfferMessageEvent = 3015;
	public static int RedeemOfferCreditsMessageEvent = 3016;
	public static int GetOffersMessageEvent = 3018;
	public static int GetOwnOffersMessageEvent = 3019;
	public static int GetMarketplaceItemStatsEvent = 3020;
	public static int DeleteFavouriteRoomMessageEvent = 20;
	public static int AddFavouriteRoomMessageEvent = 19;
	public static int GetUserFlatCatsMessageEvent = 151;
	public static int CanCreateEventMessageEvent = 345;
	public static int CreateEventMessageEvent = 346;
	public static int CancelEventMessageEvent = 347;
	public static int EditEventMessageEvent = 348;
	public static int GetRoomSettingsMessageEvent = 400;
	public static int SaveRoomSettingsMessageEvent = 401;
	public static int DeleteRoomMessageEvent = 23;
	public static int GetOfficialRoomsMessageEvent = 380;
	public static int GetPopularRoomTagsMessageEvent = 382;
	public static int UpdateNavigatorSettingsMessageEvent = 384;
	public static int GetGuestRoomMessageEvent = 385;
	public static int UpdateRoomThumbnailMessageEvent = 386;
	public static int CanCreateRoomMessageEvent = 387;
	public static int CreateFlatMessageEvent = 29;
	public static int RateFlatMessageEvent = 261;
	public static int GetPublicSpaceCastLibsMessageEvent = 388;
	public static int PopularRoomsSearchMessageEvent = 430;
	public static int RoomsWithHighestScoreSearchMessageEvent = 431;
	public static int MyFriendsRoomsSearchMessageEvent = 432;
	public static int RoomsWhereMyFriendsAreSearchMessageEvent = 433;
	public static int MyRoomsSearchMessageEvent = 434;
	public static int MyFavouriteRoomsSearchMessageEvent = 435;
	public static int MyRoomHistorySearchMessageEvent = 436;
	public static int RoomTextSearchMessageEvent = 437;
	public static int RoomTagSearchMessageEvent = 438;
	public static int LatestEventsSearchMessageEvent = 439;
	public static int ToggleStaffPickMessageEvent = 483;
	public static int GetPetCommandsMessageEvent = 3004;
	public static int OpenConnectionMessageEvent = 2;
	public static int OpenFlatConnectionMessageEvent = 391;
	public static int ChatMessageEvent = 52;
	public static int ShoutMessageEvent = 55;
	public static int WhisperMessageEvent = 56;
	public static int StartTypingMessageEvent = 317;
	public static int CancelTypingMessageEvent = 318;
	public static int SignMessageEvent = 104;
	public static int ChangeMottoMessageEvent = 484;
	public static int GoToFlatMessageEvent = 59;
	public static int GetRoomEntryDataMessageEvent = 390;
	public static int UseFurnitureMessageEvent = 392;
	public static int PickupObjectMessageEvent = 67;
	public static int MoveObjectMessageEvent = 73;
	public static int SetObjectDataMessageEvent = 74;
	public static int MoveAvatarMessageEvent = 75;
	public static int PlaceObjectMessageEvent = 90;
	public static int MoveWallItemMessageEvent = 91;
	public static int PlacePetMessageEvent = 3002;
	public static int RemovePetFromFlatMessageEvent = 3003;
	public static int ViralTeaserFoundMessageEvent = 3103;
	public static int GetMOTDMessageEvent = 3110;
	public static int GetUserNotificationsMessageEvent = 3105;
	public static int ChangeQueueMessageEvent = 211;
	public static int RoomDimmerGetPresetsMessageEvent = 341;
	public static int RoomDimmerSavePresetMessageEvent = 342;
	public static int RoomDimmerChangeStateMessageEvent = 343;
	public static int UseWallItemMessageEvent = 393;
	public static int GetItemDataMessageEvent = 83;
	public static int SetItemDataMessageEvent = 84;
	public static int RemoveItemMessageEvent = 85;
	public static int ViralFurniStatusMessageEvent = 3104;
	public static int GetPetInfoMessageEvent = 3001;
	public static int GetFurnitureAliasesMessageEvent = 215;
	public static int QuitMessageEvent = 53;
	public static int PlacePostItMessageEvent = 3254;
	public static int AddSpamWallPostItMessageEvent = 3255;
	public static int DanceMessageEvent = 93;
	public static int WaveMessageEvent = 94;
	public static int LookToMessageEvent = 79;
	public static int ThrowDiceMessageEvent = 76;
	public static int DiceOffMessageEvent = 77;
	public static int PresentOpenMessageEvent = 78;
	public static int CreditFurniRedeemMessageEvent = 183;
	public static int EnterOneWayDoorMessageEvent = 232;
	public static int SpinWheelOfFortuneMessageEvent = 247;
	public static int SetRandomStateMessageEvent = 314;
	public static int SetClothingChangeDataMessageEvent = 480;
	public static int QuestVendingWallItemMessageEvent = 3100;
	public static int OpenPetPackageMessageEvent = 3006;
	public static int OpenWelcomeGiftEvent = 3252;
	public static int KickUserMessageEvent = 95;
	public static int AssignRightsMessageEvent = 96;
	public static int RemoveRightsMessageEvent = 97;
	public static int LetUserInMessageEvent = 98;
	public static int RemoveAllRightsMessageEvent = 155;
	public static int BanUserMessageEvent = 320;
	public static int CallGuideBotMessageEvent = 440;
	public static int KickBotMessageEvent = 441;
	public static int GetUserTagsMessageEvent = 263;
	public static int GetSelectedBadgesMessageEvent = 159;
	public static int GetHabboGroupBadgesMessageEvent = 230;
	public static int GetHabboGroupDetailsMessageEvent = 231;
	public static int IgnoreUserMessageEvent = 319;
	public static int GetIgnoredUsersMessageEvent = 321;
	public static int UnignoreUserMessageEvent = 322;
	public static int RespectUserMessageEvent = 371;
	public static int RespectPetMessageEvent = 3005;
	public static int PickIssuesMessageEvent = 450;
	public static int ReleaseIssuesMessageEvent = 451;
	public static int CloseIssuesMessageEvent = 452;
	public static int GetModeratorUserInfoMessageEvent = 454;
	public static int GetUserChatlogMessageEvent = 455;
	public static int GetRoomChatlogMessageEvent = 456;
	public static int GetCfhChatlogMessageEvent = 457;
	public static int GetRoomVisitsMessageEvent = 458;
	public static int GetModeratorRoomInfoMessageEvent = 459;
	public static int ModerateRoomMessageEvent = 460;
	public static int ModAlertMessageEvent = 461;
	public static int ModMessageMessageEvent = 462;
	public static int ModKickMessageEvent = 463;
	public static int ModBanMessageEvent = 464;
	public static int ModeratorActionMessageEvent = 200;
	public static int CallForHelpMessageEvent = 453;
	public static int GetPendingCallsForHelpMessageEvent = 237;
	public static int DeletePendingCallsForHelpMessageEvent = 238;
	public static int GetClientFaqsMessageEvent = 416;
	public static int GetFaqCategoriesMessageEvent = 417;
	public static int GetFaqTextMessageEvent = 418;
	public static int SearchFaqsMessageEvent = 419;
	public static int GetFaqCategoryMessageEvent = 420;
	public static int ChangeEmailEvent = 3253;
	public static int ScrGetUserInfoMessageEvent = 26;
	public static int GetAchievementShareIdEvent = 481;
	public static int ResetUnseenItemsEvent = 3111;
	public static int PurchaseFromCatalogEvent = 100;
	public static int PurchaseFromCatalogAsGiftEvent = 472;
	public static int GetGiftWrappingConfigurationEvent = 473;
	public static int SelectClubGiftEvent = 475;
	public static int GetCatalogIndexEvent = 101;
	public static int GetCatalogPageEvent = 102;
	public static int RedeemVoucherMessageEvent = 129;
	public static int GetIsOfferGiftableEvent = 3030;
	public static int GetClubOffersMessageEvent = 3031;
	public static int GetSellablePetBreedsEvent = 3007;
	public static int MarkCatalogNewAdditionsPageOpenedEvent = 3034;
	public static int GetHabboClubExtendOfferMessageEvent = 3035;
	public static int PurchaseVipMembershipExtensionEvent = 3036;
	public static int PurchaseBasicMembershipExtensionEvent = 3037;
	public static int GetHabboBasicMembershipExtendOfferEvent = 3038;
	public static int GetRecyclerPrizesMessageEvent = 412;
	public static int GetRecyclerStatusMessageEvent = 413;
	public static int RecycleItemsMessageEvent = 414;
	public static int GetRoomAdMessageEvent = 126;
	public static int GetInterstitialMessageEvent = 182;
	public static int LatencyPingRequestMessageEvent = 315;
	public static int LatencyPingReportMessageEvent = 316;
	public static int PerformanceLogMessageEvent = 421;
	public static int LagWarningReportMessageEvent = 422;
	public static int EventLogMessageEvent = 482;
	public static int VoteAnswerMessageEvent = 112;
	public static int PollRejectEvent = 235;
	public static int PollStartEvent = 234;
	public static int PollAnswerEvent = 236;
	public static int ExitLockerRoomMessageEvent = 108;
	public static int ChangeRoomMessageEvent = 111;
	public static int TryBusMessageEvent = 113;
	public static int ApproveNameMessageEvent = 42;
	public static int GetSoundMachinePlayListMessageEvent = 245;
	public static int GetNowPlayingMessageEvent = 249;
	public static int GetSongInfoMessageEvent = 221;
	public static int GetSoundSettingsEvent = 228;
	public static int SetSoundSettingsEvent = 229;
	public static int AddJukeboxDiskEvent = 0xFF;
	public static int RemoveJukeboxDiskEvent = 0x0100;
	public static int GetJukeboxPlayListMessageEvent = 258;
	public static int GetUserSongDisksMessageEvent = 259;
	public static int GetWardrobeMessageEvent = 375;
	public static int SaveWardrobeOutfitMessageEvent = 376;
	public static int ChangeUserNameMessageEvent = 470;
	public static int CheckUserNameMessageEvent = 471;
	public static int UpdateFigureDataMessageEvent = 44;
	public static int UpdateTriggerMessageEvent = 3050;
	public static int UpdateActionMessageEvent = 3051;
	public static int UpdateConditionMessageEvent = 3052;
	public static int OpenMessageEvent = 3053;
	public static int ApplySnapshotMessageEvent = 3054;
	public static int GetQuestsMessageEvent = 3101;
	public static int AcceptQuestMessageEvent = 3102;
	public static int RejectQuestMessageEvent = 3106;
	public static int OpenQuestTrackerMessageEvent = 3107;
	public static int StartCampaignMessageEvent = 3108;
	public static int FriendRequestQuestCompleteMessageEvent = 3210;
	public static int FaceBookIsLoggedOnMessageEvent = 3300;
	public static int FaceBookIsLoggedOffMessageEvent = 3301;
	public static int FaceBookInitiateAddFriendsMessageEvent = 3311;

	public static String valueOfId(int Id)
	{
		Incoming IncomingClass = new Incoming();

		Field[] fields;
		try
		{
			fields = IncomingClass.getClass().getDeclaredFields();

			for (Field field : fields)
			{
				if (field.getInt(field.getName()) == Id)
				{
					return field.getName();
				}
			}
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
		return "";
	}
}
